{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels: {{ include "kyverno.labels" . | nindent 4 }}
    app: kyverno
  name: {{ template "kyverno.fullname" . }}
  namespace: {{ template "kyverno.namespace" . }}
spec:
  podSelector:
    matchLabels:
      app: kyverno
  policyTypes:
  - Ingress
  {{- if .Values.networkPolicy.ingressFrom }}
  ingress:
  - from:
    {{- with .Values.networkPolicy.ingressFrom }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    ports:
    - protocol: TCP
      port: 9443 # webhook access
  # Allow prometheus scrapes for metrics
  {{- if .Values.metricsService.create }}
    - protocol: TCP
      port: {{ .Values.metricsService.port }}
  {{- end }}
  {{- else }}
  ingress:
    - {}
  {{- end }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-prometheus
  namespace: kyverno
  labels:
    app: kyverno
spec:
  podSelector:
    matchLabels:
      app: kyverno
  {{- if .Values.networkPolicy.prometheusMatchLabels }}
  ingress:
  - from:
    - podSelector:
        matchLabels:
          {{- with .Values.networkPolicy.prometheusMatchLabels }}
            {{- toYaml . | nindent 4 }}
          {{- end }}
    ports:
    # Webhook access
    - protocol: TCP
      port: 9443
    # Allow prometheus scrape for metrics
    - protocol: TCP
      port: 8000
  {{- else }}
  ingress:
  - {}
  {{- end }}
  policyTypes:
    - Ingress
    - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-apiserver
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  # Allow ingress from kube-apiserver on port 9443
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
        - podSelector:
            matchLabels:
              component: kube-apiserver
              tier: control-plane
      ports:
        - port: 9443
  # If openEgress is true allow all egress traffic else allow egress to only kube-apiserver on port 9443
  {{- if .Values.networkPolicy.openEgress }}
  egress:
  - {}
  {{- else }}
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
        - podSelector:
            matchLabels:
              component: kube-apiserver
              tier: control-plane
      ports:
        - port: 9443
  {{- end }}
{{- end }}
